// <auto-generated />
namespace EProductivity.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstDatabaseProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstDatabaseProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201407122242019_FirstDatabaseProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
