// <auto-generated />
namespace EProductivity.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FirstDatabaseData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstDatabaseData));
        
        string IMigrationMetadata.Id
        {
            get { return "201407312158257_FirstDatabaseData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
